//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForumApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account Information.
        /// </summary>
        public static string AccountInformation {
            get {
                return ResourceManager.GetString("AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add mesasge.
        /// </summary>
        public static string AddMesasgeTitle {
            get {
                return ResourceManager.GetString("AddMesasgeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message added!.
        /// </summary>
        public static string AddMessage {
            get {
                return ResourceManager.GetString("AddMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back to Forum.
        /// </summary>
        public static string BackToForum {
            get {
                return ResourceManager.GetString("BackToForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type user changed!.
        /// </summary>
        public static string ChangeTypeUser {
            get {
                return ResourceManager.GetString("ChangeTypeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change Type User.
        /// </summary>
        public static string ChangeTypeUserBtn {
            get {
                return ResourceManager.GetString("ChangeTypeUserBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error change type user!.
        /// </summary>
        public static string ChangeTypeUserError {
            get {
                return ResourceManager.GetString("ChangeTypeUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure, that you want delete message?.
        /// </summary>
        public static string ConfirmDelMes {
            get {
                return ResourceManager.GetString("ConfirmDelMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Count Messages.
        /// </summary>
        public static string CountMessages {
            get {
                return ResourceManager.GetString("CountMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Topic created!.
        /// </summary>
        public static string CreateTopic {
            get {
                return ResourceManager.GetString("CreateTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create Topic.
        /// </summary>
        public static string CreateTopicTitle {
            get {
                return ResourceManager.GetString("CreateTopicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message deleted!.
        /// </summary>
        public static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error delete message!.
        /// </summary>
        public static string DeleteMessageError {
            get {
                return ResourceManager.GetString("DeleteMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete Message.
        /// </summary>
        public static string DeleteMessageTitle {
            get {
                return ResourceManager.GetString("DeleteMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [Edit].
        /// </summary>
        public static string EditInBlock {
            get {
                return ResourceManager.GetString("EditInBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message edited!.
        /// </summary>
        public static string EditMessage {
            get {
                return ResourceManager.GetString("EditMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit Message.
        /// </summary>
        public static string EditMessageTitle {
            get {
                return ResourceManager.GetString("EditMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Topic edited!.
        /// </summary>
        public static string EditTopic {
            get {
                return ResourceManager.GetString("EditTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit Topic Name.
        /// </summary>
        public static string EditTopicNameTitle {
            get {
                return ResourceManager.GetString("EditTopicNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message error.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Topic error.
        /// </summary>
        public static string ErrorTopic {
            get {
                return ResourceManager.GetString("ErrorTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Topic with such name already exists..
        /// </summary>
        public static string ErrorTopicName {
            get {
                return ResourceManager.GetString("ErrorTopicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Forum.
        /// </summary>
        public static string Forum {
            get {
                return ResourceManager.GetString("Forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Good bye, .
        /// </summary>
        public static string GoodBye {
            get {
                return ResourceManager.GetString("GoodBye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect data input.
        /// </summary>
        public static string IncorrectData {
            get {
                return ResourceManager.GetString("IncorrectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect password!.
        /// </summary>
        public static string IncorrectPass {
            get {
                return ResourceManager.GetString("IncorrectPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input your message.
        /// </summary>
        public static string InputMessage {
            get {
                return ResourceManager.GetString("InputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last message.
        /// </summary>
        public static string LastMessage {
            get {
                return ResourceManager.GetString("LastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message Date.
        /// </summary>
        public static string MessageDate {
            get {
                return ResourceManager.GetString("MessageDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have been banned! The entrance isn&apos;t executed..
        /// </summary>
        public static string MessageForBanned {
            get {
                return ResourceManager.GetString("MessageForBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Type User.
        /// </summary>
        public static string NewTypeUser {
            get {
                return ResourceManager.GetString("NewTypeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на of.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passwords don&apos;t coincide!.
        /// </summary>
        public static string PassConfirmed {
            get {
                return ResourceManager.GetString("PassConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;p&gt;Password has to be in the range 8-20.&lt;/p&gt;.
        /// </summary>
        public static string PassValid {
            get {
                return ResourceManager.GetString("PassValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration is successfully complete!.
        /// </summary>
        public static string RegistrationComplete {
            get {
                return ResourceManager.GetString("RegistrationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration Date.
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration error.
        /// </summary>
        public static string RegistrationError {
            get {
                return ResourceManager.GetString("RegistrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Repeat Password.
        /// </summary>
        public static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show User Messages.
        /// </summary>
        public static string ShowUserMessagesBtn {
            get {
                return ResourceManager.GetString("ShowUserMessagesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show Users.
        /// </summary>
        public static string ShowUsers {
            get {
                return ResourceManager.GetString("ShowUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;p&gt;Text message has to be in the range 1-4000.&lt;/p&gt;.
        /// </summary>
        public static string TextMessageValid {
            get {
                return ResourceManager.GetString("TextMessageValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Topic.
        /// </summary>
        public static string Topic {
            get {
                return ResourceManager.GetString("Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Topic Name.
        /// </summary>
        public static string TopicName {
            get {
                return ResourceManager.GetString("TopicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;p&gt;The topic name has to be in the range 4-20.&lt;/p&gt;.
        /// </summary>
        public static string TopicNameValid {
            get {
                return ResourceManager.GetString("TopicNameValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type User.
        /// </summary>
        public static string TypeUser {
            get {
                return ResourceManager.GetString("TypeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The user exists!.
        /// </summary>
        public static string UserEx {
            get {
                return ResourceManager.GetString("UserEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;p&gt;User Name has to be in the range 4-20.&lt;/p&gt;.
        /// </summary>
        public static string UserNameValid {
            get {
                return ResourceManager.GetString("UserNameValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The user doesn&apos;t exist.
        /// </summary>
        public static string UserNotEx {
            get {
                return ResourceManager.GetString("UserNotEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome, .
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
